---
# Source: kube-prometheus-stack/templates/alertmanager/alertmanager.yaml
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: release-name-kube-promethe-alertmanager
  namespace: default
  labels:
    app: kube-prometheus-stack-alertmanager

    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "51.2.0"
    app.kubernetes.io/part-of: kube-prometheus-stack
    chart: kube-prometheus-stack-51.2.0
    release: "release-name"
    heritage: "Helm"
spec:
  image: "quay.io/prometheus/alertmanager:v0.26.0"
  version: v0.26.0
  replicas: 1
  listenLocal: false
  serviceAccountName: release-name-kube-promethe-alertmanager
  externalUrl: http://release-name-kube-promethe-alertmanager.default:9093
  paused: false
  logFormat: "logfmt"
  logLevel: "info"
  retention: "120h"
  alertmanagerConfigSelector: {}
  alertmanagerConfigNamespaceSelector: {}
  routePrefix: "/"
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  portName: http-web
