name: Run 'PyLint' command
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
    branches:
      - master
      - main
    paths:
      - '**.py'
permissions:
  contents: read
jobs:
  pyLint_run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install -r tests/test-requirements.txt
      - name: Run Pylint with a minimum threshold
        run: |
          pylint --fail-under=9 --output-format=text **/*.py
