name: Build and publish a new image
on:
  release:
    types:
      - published
permissions:
  contents: write
  packages: write
jobs:
  new_image_build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup release
        uses: ./.github/workflows/common-setup.yaml@main
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.REPO_USER }}/${{ env.REPO_NAME }}:${{ env.LATEST_RELEASE_TAG }}
            ghcr.io/${{ env.REPO_USER }}/${{ env.REPO_NAME }}:latest
      - name: Set up anybadge
        run: |
          python -m pip install --upgrade pip
          pip install anybadge
      - name: Generate badge
        run: |
          anybadge --value ghcr.io/${{ env.REPO_USER }}/${{ env.REPO_NAME }}:${{ env.LATEST_RELEASE_TAG }} \
          --file=./.github/badges/image.svg --label 'ghcr.io image' --color fuchsia --overwrite
      - name: Commit badge to repo
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ./.github/badges/image.svg
          # Check for changes
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "Update image badge [skip ci]"
          git push
